# service config
service_name : self_coder_service
port: 8687

max_workers: 5     # multithread
max_retries: 3     # Number of retry attempts after failure

connect_timeout: 15      # Wait the port to be listend
render_timeout: 25    # max gradio rendering time 


# openai config
base_url: http://localhost:8001/v1
api_key: sk-XXXXXX
model: Qwen3

# base_url: http://oneapi.aimc.offline/v1
# api_key: sk-XXXX
# model: gpt-4.1-mini
